# Generated by Django 2.0.5 on 2018-05-20 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('management', models.BooleanField(default=0, verbose_name='management')),
                ('data_created', models.DateTimeField(auto_now=True, verbose_name='data created')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'playlist',
                'verbose_name_plural': 'playlist',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=0, verbose_name='like')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='playlists.Playlist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='songs.Songs')),
            ],
        ),
        migrations.CreateModel(
            name='VoteTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateTimeField(verbose_name='begin')),
                ('final', models.DateTimeField(verbose_name='final')),
            ],
        ),
    ]
