# Generated by Django 2.0.5 on 2018-06-03 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
        ('playlists', '0002_auto_20180604_0041'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicalPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(verbose_name='slug name')),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistPlay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_likes', models.PositiveIntegerField(default=0, verbose_name='count song')),
            ],
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='management',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='songs',
        ),
        migrations.AddField(
            model_name='playlist',
            name='is_public',
            field=models.BooleanField(db_index=True, default=0, verbose_name='management'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='vote_time',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='playlists.VoteTime'),
        ),
        migrations.RemoveField(
            model_name='vote',
            name='like',
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('playlist', 'song')},
        ),
        migrations.AddField(
            model_name='playlistplay',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='playlists.Playlist'),
        ),
        migrations.AddField(
            model_name='playlistplay',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='songs.Song'),
        ),
        migrations.AlterUniqueTogether(
            name='playlistplay',
            unique_together={('playlist', 'song')},
        ),
    ]
