# Generated by Django 2.0.5 on 2018-06-03 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0003_auto_20180604_0200'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MusicalPreference',
        ),
    ]
