# Generated by Django 2.0.5 on 2018-06-03 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0003_auto_20180604_0200'),
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='use_playlist',
            field=models.ManyToManyField(to='playlists.Playlist'),
        ),
    ]
