# Generated by Django 2.0.5 on 2018-06-03 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_auto_20180604_0229'),
        ('userauth', '0002_user_use_playlist'),
    ]

    operations = [
    ]
