# Generated by Django 2.0.5 on 2018-06-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('origin_name', models.CharField(max_length=255, verbose_name='origin name')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('authors', models.ManyToManyField(related_name='songs', to='songs.AuthorSong')),
            ],
        ),
    ]
