# Generated by Django 2.0.5 on 2018-08-01 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='authors',
        ),
    ]
